export type CardData = {
  id: number;
  name: string;
  type: string;
  deck: string;
  image: string;
  alt_image: string | null;
  banned: boolean;
  is_no: boolean;
  dealt: number | null;
  drafted: number | null;
  played: number | null;
  won: number | null;
  ADP: number | null;
  play_ratio: number | null;
  win_ratio: number | null;
  PWR: number | null;
  PWR_no_log: number | null;
  PWR_normalized: number | null;
};
