export type CardData = {
    name:string,
    img_name:string,
    dealt:number,
    drafted:number,
    played:number,
    won:number,
    ADP:number,
    play_ratio:number,
    win_ratio:number,
    PWR:number,
    PWR_no_log:number,
    PWR_normalized:number|null,
    Deck:string,
    id:number,
} 